id: "gamecube-test"
version: "1.0.0"
type: "application"
dependencies:
  - id: am-lang-core
    type: local
    path: ../..
platforms:
  - id: libc
    abstract: true
  - id: "linux-x64"
    extends: libc
    gccCommand: "gcc"
  - id: "nintendo-ppc"
    extends: libc
    gccCommand: "powerpc-eabi-gcc -O2 -mogc -mcpu=750 -meabi -mhard-float"
    additionalIncludePaths:
      - /opt/devkitpro/libogc2/gamecube/include
    gccAdditionalOptions:
      - -DAM_PLATFORM_NINTENDO_PPC
      - -DGEKKO
    gccLibraryPaths:
      - /opt/devkitpro/libogc2/gamecube/lib
      - /opt/devkitpro/devkitPPC/powerpc-eabi/lib
    gccAdditionalLibraries:
      - ogc
      - m
buildTargets:
  - id: "linux-x64"
    platform: "linux-x64"
  - id: "gamecube-docker"
    platform: "nintendo-ppc"
    commands:
      - docker run --rm -v ${build_dir}:/src -e USE_CCACHE=1 -i webhdx/devkitppc-libogc2 /entrypoint.sh -f nintendo-ppc.makefile all
