
id: am-lang-core
version: 0.1.0
type: library
platforms:
  - id: libc
    abstract: true
    additonalHeaders:
      - core.h 
    additonalImplementations: 
      - core.c
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    additonalHeaders:
      - amigaos/amiga.h
    additonalImplementations: 
      - amigaos/amiga.c
    gccAdditionalOptions:
      - -noixemul
  - id: linux-x64
    extends: libc
    gccCommand: gcc
buildTargets:
  - id: amigaos_docker_win_anders
    commands:
      - docker run -v ${build_dir}:/host -i d931759c3883 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_matebook_anders
    commands:
      - docker run -v ${build_dir}:/host -i 265cc923e013 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_macm1_anders
    commands:
      - make -f linux-x64.makefile
#      - docker run -v ${build_dir}:/host -i 0205cf669adf make -f amigaos.makefile -C /host all
    