
id: am-lang-core
version: 0.1.0
type: library
platforms:
  - id: amigaos
    gccCommand: m68k-amigaos-gcc
    additonalHeaders:
      - core.h 
      - amigaos/amiga.h
    additonalImplementations: 
      - core.c
      - amigaos/amiga.c
    
