
id: am-lang-core
version: 0.1.0
type: library
platforms:
  - id: libc
    abstract: true
    additionalHeaders:
      - core.h 
    additionalImplementations: 
      - inputFilename: core.c     
        outputFilename: core.o
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    additionalHeaders:
      - amiga.h
    additionalImplementations: 
      - inputFilename: amiga.c     
        outputFilename: amiga.o
    gccAdditionalOptions:
      - -noixemul
  - id: linux-x64
    extends: libc
    gccCommand: gcc
buildTargets:
  - id: amigaos_docker_win_anders
    commands:
      - docker run -v ${build_dir}:/host -i d931759c3883 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_matebook_anders
    commands:
      - docker run -v ${build_dir}:/host -i 265cc923e013 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_macm1_anders
    commands:
      - docker run -v ${build_dir}:/host -i 0205cf669adf make -f amigaos.makefile -C /host all
  - id: macos
    commands:
      - make -f linux-x64.makefile
  - id: linux_x64
    commands:
      - make -f linux-x64.makefile
  - id: windows_docker
    commands: 
      - docker run --rm -v "${build_dir}":/usr/src/ -w /usr/src/ gcc:12.1 make -f linux-x64.makefile
    