
id: am-lang-core
version: 0.1.0
type: library
platforms:
  - id: libc
    abstract: true
    additionalHeaders:
      - core.h 
    additionalCSources: 
      - inputFilename: core.c     
        outputFilename: core.o
  - id: amigaos
    extends: libc
    gccCommand: m68k-amigaos-gcc
    additionalHeaders:
      - amiga.h
    additionalCSources: 
      - inputFilename: amiga.c     
        outputFilename: amiga.o
    gccAdditionalOptions:
      - -noixemul
  - id: m68k-ataritos
    extends: libc
    gccCommand: m68k-ataritos-gcc
#    additionalHeaders:
#      - atari.h
#    additionalCSources: 
#      - inputFilename: atari.c     
#        outputFilename: atari.o
    gccAdditionalOptions:
#      - -noixemul
  - id: linux-x64
    extends: libc
    gccCommand: gcc
  - id: morphos-ppc
    extends: libc
    gccCommand: ppc-morphos-gcc
    additionalHeaders:
      - morphos.h
    additionalCSources: 
      - inputFilename: morphos.c     
        outputFilename: morphos.o
    gccAdditionalOptions:
      - -noixemul
  - id: aros-x86-64
    extends: libc
    gccCommand: gcc
    additionalHeaders:
      - aros.h
    additionalCSources: 
      - inputFilename: aros.c     
        outputFilename: aros.o
    gccAdditionalOptions:
      - -noixemul
buildTargets:
  - id: amigaos_docker_win_anders
    commands:
      - docker run -v ${build_dir}:/host -i d931759c3883 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_matebook_anders
    commands:
      - docker run -v ${build_dir}:/host -i 265cc923e013 make -f amigaos.makefile -C /host all
  - id: amigaos_docker_macm1_anders
    commands:
      - docker run -v ${build_dir}:/host -i 0205cf669adf make -f amigaos.makefile -C /host all
  - id: macos
    commands:
      - make -f linux-x64.makefile
  - id: linux_x64
    commands:
      - make -f linux-x64.makefile
  - id: windows_docker
    commands: 
      - docker run --rm -v "${build_dir}":/usr/src/ -w /usr/src/ gcc:12.1 make -f linux-x64.makefile
  - id: morphos-ppc_docker
    platform: morphos-ppc
    commands:
      - docker run --rm -v "${build_dir}":/work -e USER=$( id -u ) -e GROUP=$( id -g ) -it amigadev/crosstools:ppc-morphos make -f morphos_ppc.makefile -C /work all
  - id: morphos-ppc_docker_win
    commands:
      - docker run --rm -v "${build_dir}":/work -e -i amigadev/crosstools:ppc-morphos make -f morphos-ppc.makefile -C /work all
  - id: aros-x86-64_docker_win
    commands: 
      - docker run --rm -v "${build_dir}":/work -i amigadev/crosstools:x86_64-aros make aros-x86-64.makefile all
      #-v /path/to/extra/ppc-morphos/lib:/tools/usr/lib -v /path/to/extra/ppc-morphos/include:/tools/usr/include
  #-v /path/to/extra/ppc-morphos/lib:/tools/usr/lib -v /path/to/extra/ppc-morphos/include:/tools/usr/include
  - id: m68k-ataritos_docker:
    platform: m68k-ataritos
    commands:
      - docker run -v ${build_dir}:/host -i nokturnaldock/atari_development:latest make -f m68k-ataritos.makefile -C /host all
