#include <libc/core.h>
#include <Am/IO/BinaryStream.h>
#include <aros-x86-64/Am/IO/BinaryStream.h>
#include <Am/IO/Stream.h>
#include <Am/Lang/Array.h>
#include <Am/Lang/Byte.h>
#include <Am/Lang/Long.h>
#include <Am/Lang/Int.h>
#include <Am/Lang/Short.h>
#include <libc/core_inline_functions.h>
