id: "thread-test"
version: "1.0.0"
type: "application"
dependencies:
  - id: am-lang-core
    type: local
    path: ../..
platforms:
  - id: libc
    abstract: true
  - id: "linux-x64"
    extends: libc
    gccCommand: "gcc"
  - id: "amigaos"
    extends: libc
    gccCommand: "m68k-amigaos-gcc -O3"
    gccAdditionalOptions:
      - -noixemul
    additionalLinkerFlags:
      - -noixemul
buildTargets:
  - id: "linux-x64"
    platform: "linux-x64"
  - id: "amigaos-docker"
    platform: "amigaos"
    dockerBuild:
      image: amiga-gcc:latest
      buildPath: /host
