#pragma once
#include <libc/core.h>
#include <Am/IO/File.h>
#include <Am/Lang/Object.h>
#include <Am/Lang/String.h>
#include <Am/Lang/Array.h>
#include <Am/Collections/List.h>
#include <Am/Lang/Bool.h>
#include <Am/Lang/Int.h>
#include <Am/Collections/Iterator.h>
#include <Am/Lang/UInt.h>
